// Generated by gencpp from file sip_scenario/AccessToFloor.msg
// DO NOT EDIT!


#ifndef SIP_SCENARIO_MESSAGE_ACCESSTOFLOOR_H
#define SIP_SCENARIO_MESSAGE_ACCESSTOFLOOR_H

#include <ros/service_traits.h>


#include <sip_scenario/AccessToFloorRequest.h>
#include <sip_scenario/AccessToFloorResponse.h>


namespace sip_scenario
{

struct AccessToFloor
{

typedef AccessToFloorRequest Request;
typedef AccessToFloorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AccessToFloor
} // namespace sip_scenario


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sip_scenario::AccessToFloor > {
  static const char* value()
  {
    return "80c7dd3d66bf2a99c16e42e7089d1344";
  }

  static const char* value(const ::sip_scenario::AccessToFloor&) { return value(); }
};

template<>
struct DataType< ::sip_scenario::AccessToFloor > {
  static const char* value()
  {
    return "sip_scenario/AccessToFloor";
  }

  static const char* value(const ::sip_scenario::AccessToFloor&) { return value(); }
};


// service_traits::MD5Sum< ::sip_scenario::AccessToFloorRequest> should match 
// service_traits::MD5Sum< ::sip_scenario::AccessToFloor > 
template<>
struct MD5Sum< ::sip_scenario::AccessToFloorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sip_scenario::AccessToFloor >::value();
  }
  static const char* value(const ::sip_scenario::AccessToFloorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sip_scenario::AccessToFloorRequest> should match 
// service_traits::DataType< ::sip_scenario::AccessToFloor > 
template<>
struct DataType< ::sip_scenario::AccessToFloorRequest>
{
  static const char* value()
  {
    return DataType< ::sip_scenario::AccessToFloor >::value();
  }
  static const char* value(const ::sip_scenario::AccessToFloorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sip_scenario::AccessToFloorResponse> should match 
// service_traits::MD5Sum< ::sip_scenario::AccessToFloor > 
template<>
struct MD5Sum< ::sip_scenario::AccessToFloorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sip_scenario::AccessToFloor >::value();
  }
  static const char* value(const ::sip_scenario::AccessToFloorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sip_scenario::AccessToFloorResponse> should match 
// service_traits::DataType< ::sip_scenario::AccessToFloor > 
template<>
struct DataType< ::sip_scenario::AccessToFloorResponse>
{
  static const char* value()
  {
    return DataType< ::sip_scenario::AccessToFloor >::value();
  }
  static const char* value(const ::sip_scenario::AccessToFloorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIP_SCENARIO_MESSAGE_ACCESSTOFLOOR_H
