// Generated by gencpp from file sip_scenario/LampInput.msg
// DO NOT EDIT!


#ifndef SIP_SCENARIO_MESSAGE_LAMPINPUT_H
#define SIP_SCENARIO_MESSAGE_LAMPINPUT_H

#include <ros/service_traits.h>


#include <sip_scenario/LampInputRequest.h>
#include <sip_scenario/LampInputResponse.h>


namespace sip_scenario
{

struct LampInput
{

typedef LampInputRequest Request;
typedef LampInputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LampInput
} // namespace sip_scenario


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sip_scenario::LampInput > {
  static const char* value()
  {
    return "585976945ba2a0bae2bfb5564650a375";
  }

  static const char* value(const ::sip_scenario::LampInput&) { return value(); }
};

template<>
struct DataType< ::sip_scenario::LampInput > {
  static const char* value()
  {
    return "sip_scenario/LampInput";
  }

  static const char* value(const ::sip_scenario::LampInput&) { return value(); }
};


// service_traits::MD5Sum< ::sip_scenario::LampInputRequest> should match 
// service_traits::MD5Sum< ::sip_scenario::LampInput > 
template<>
struct MD5Sum< ::sip_scenario::LampInputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sip_scenario::LampInput >::value();
  }
  static const char* value(const ::sip_scenario::LampInputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sip_scenario::LampInputRequest> should match 
// service_traits::DataType< ::sip_scenario::LampInput > 
template<>
struct DataType< ::sip_scenario::LampInputRequest>
{
  static const char* value()
  {
    return DataType< ::sip_scenario::LampInput >::value();
  }
  static const char* value(const ::sip_scenario::LampInputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sip_scenario::LampInputResponse> should match 
// service_traits::MD5Sum< ::sip_scenario::LampInput > 
template<>
struct MD5Sum< ::sip_scenario::LampInputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sip_scenario::LampInput >::value();
  }
  static const char* value(const ::sip_scenario::LampInputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sip_scenario::LampInputResponse> should match 
// service_traits::DataType< ::sip_scenario::LampInput > 
template<>
struct DataType< ::sip_scenario::LampInputResponse>
{
  static const char* value()
  {
    return DataType< ::sip_scenario::LampInput >::value();
  }
  static const char* value(const ::sip_scenario::LampInputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIP_SCENARIO_MESSAGE_LAMPINPUT_H
