// Generated by gencpp from file sip_scenario/LampInputRequest.msg
// DO NOT EDIT!


#ifndef SIP_SCENARIO_MESSAGE_LAMPINPUTREQUEST_H
#define SIP_SCENARIO_MESSAGE_LAMPINPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace sip_scenario
{
template <class ContainerAllocator>
struct LampInputRequest_
{
  typedef LampInputRequest_<ContainerAllocator> Type;

  LampInputRequest_()
    : target()  {
    }
  LampInputRequest_(const ContainerAllocator& _alloc)
    : target(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _target_type;
  _target_type target;




  typedef boost::shared_ptr< ::sip_scenario::LampInputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sip_scenario::LampInputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LampInputRequest_

typedef ::sip_scenario::LampInputRequest_<std::allocator<void> > LampInputRequest;

typedef boost::shared_ptr< ::sip_scenario::LampInputRequest > LampInputRequestPtr;
typedef boost::shared_ptr< ::sip_scenario::LampInputRequest const> LampInputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sip_scenario::LampInputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sip_scenario::LampInputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sip_scenario

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sip_scenario::LampInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sip_scenario::LampInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sip_scenario::LampInputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bff3d00c7def8278f440fadd57c0653";
  }

  static const char* value(const ::sip_scenario::LampInputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bff3d00c7def827ULL;
  static const uint64_t static_value2 = 0x8f440fadd57c0653ULL;
};

template<class ContainerAllocator>
struct DataType< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sip_scenario/LampInputRequest";
  }

  static const char* value(const ::sip_scenario::LampInputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point target\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::sip_scenario::LampInputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LampInputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sip_scenario::LampInputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sip_scenario::LampInputRequest_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIP_SCENARIO_MESSAGE_LAMPINPUTREQUEST_H
