// Generated by gencpp from file sip_scenario/StopScenario.msg
// DO NOT EDIT!


#ifndef SIP_SCENARIO_MESSAGE_STOPSCENARIO_H
#define SIP_SCENARIO_MESSAGE_STOPSCENARIO_H

#include <ros/service_traits.h>


#include <sip_scenario/StopScenarioRequest.h>
#include <sip_scenario/StopScenarioResponse.h>


namespace sip_scenario
{

struct StopScenario
{

typedef StopScenarioRequest Request;
typedef StopScenarioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopScenario
} // namespace sip_scenario


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sip_scenario::StopScenario > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sip_scenario::StopScenario&) { return value(); }
};

template<>
struct DataType< ::sip_scenario::StopScenario > {
  static const char* value()
  {
    return "sip_scenario/StopScenario";
  }

  static const char* value(const ::sip_scenario::StopScenario&) { return value(); }
};


// service_traits::MD5Sum< ::sip_scenario::StopScenarioRequest> should match 
// service_traits::MD5Sum< ::sip_scenario::StopScenario > 
template<>
struct MD5Sum< ::sip_scenario::StopScenarioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sip_scenario::StopScenario >::value();
  }
  static const char* value(const ::sip_scenario::StopScenarioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sip_scenario::StopScenarioRequest> should match 
// service_traits::DataType< ::sip_scenario::StopScenario > 
template<>
struct DataType< ::sip_scenario::StopScenarioRequest>
{
  static const char* value()
  {
    return DataType< ::sip_scenario::StopScenario >::value();
  }
  static const char* value(const ::sip_scenario::StopScenarioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sip_scenario::StopScenarioResponse> should match 
// service_traits::MD5Sum< ::sip_scenario::StopScenario > 
template<>
struct MD5Sum< ::sip_scenario::StopScenarioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sip_scenario::StopScenario >::value();
  }
  static const char* value(const ::sip_scenario::StopScenarioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sip_scenario::StopScenarioResponse> should match 
// service_traits::DataType< ::sip_scenario::StopScenario > 
template<>
struct DataType< ::sip_scenario::StopScenarioResponse>
{
  static const char* value()
  {
    return DataType< ::sip_scenario::StopScenario >::value();
  }
  static const char* value(const ::sip_scenario::StopScenarioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIP_SCENARIO_MESSAGE_STOPSCENARIO_H
