// Generated by gencpp from file sip_scenario/StopScenarioRequest.msg
// DO NOT EDIT!


#ifndef SIP_SCENARIO_MESSAGE_STOPSCENARIOREQUEST_H
#define SIP_SCENARIO_MESSAGE_STOPSCENARIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sip_scenario
{
template <class ContainerAllocator>
struct StopScenarioRequest_
{
  typedef StopScenarioRequest_<ContainerAllocator> Type;

  StopScenarioRequest_()
    {
    }
  StopScenarioRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopScenarioRequest_

typedef ::sip_scenario::StopScenarioRequest_<std::allocator<void> > StopScenarioRequest;

typedef boost::shared_ptr< ::sip_scenario::StopScenarioRequest > StopScenarioRequestPtr;
typedef boost::shared_ptr< ::sip_scenario::StopScenarioRequest const> StopScenarioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sip_scenario::StopScenarioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sip_scenario

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sip_scenario::StopScenarioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sip_scenario/StopScenarioRequest";
  }

  static const char* value(const ::sip_scenario::StopScenarioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::sip_scenario::StopScenarioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopScenarioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sip_scenario::StopScenarioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sip_scenario::StopScenarioRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SIP_SCENARIO_MESSAGE_STOPSCENARIOREQUEST_H
